import i18n from "i18next";
import { initReactI18next } from "react-i18next";

void i18n.use(initReactI18next).init({
    lng: "en",
    resources: {
        en: {
            translation: {
                welcome: "Welcome",
                allScenarios: "All Scenarios",
                failedScenarios: "Failed Scenarios",
                pendingScenarios: "Pending Scenarios",
                abortedScenarios: "Aborted Scenarios",
                searchResults: "Search Results",
                searchPlaceholder: "search in scenarios",
                summary: "Summary",
                tags: "Tags",
                classes: "Classes",
                bookmarks: "Bookmarks",
                successful: "Successful",
                failed: "Failed",
                pending: "Pending",
                aborted: "Aborted",
                total: "Total",
                filtered: "Filtered",
                package: "Package",
                loading: "Loading",
                metadataFooter: "Data generated by JGiven {{version}} on {{created}}",
                htmlAppVersion: "HTML App {{version}}.",
                searchedFor: "Searched for '{{query}}'",
                noFailedScenarios: "There are no failed scenarios. Keep rocking!",
                oneFailedScenario: "There is only 1 failed scenario. You nearly made it!",
                manyFailedScenarios: "There are {{count}} failed scenarios",
                noPendingScenarios: "There are no pending scenarios. Keep rocking!",
                onePendingScenario: "There is only 1 pending scenario. You nearly made it!",
                manyPendingScenarios: "There are {{count}} pending scenarios",
                noAbortedScenarios: "There are no aborted scenarios. Keep rocking!",
                oneAbortedScenario: "There is only 1 aborted scenario. You nearly made it!",
                manyAbortedScenarios: "There are {{count}} aborted scenarios",
                groupBy: "Group By",
                sortBy: "Sort By",
                status: "Status",
                tagsDropdown: "Tags",
                classesDropdown: "Classes",
                cases: "Cases",
                collapseAll: "Collapse All",
                expandAll: "Expand All",
                printPage: "Print Page",
                addBookmark: "Add Bookmark"
            }
        }
    },
    interpolation: { escapeValue: false }
});

export default i18n;
